# Uncomment the next line to define a global platform for your project
#platform :osx

target 'jphacks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for jphacks
	pod 'Alamofire'
  target 'jphacksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'jphacksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
